// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbNAf6SQ42KkGIjHth8Mm3rm5atB5CJHQ',
    appId: '1:139042789017:android:0e7a91e7dab0b66a750a08',
    messagingSenderId: '139042789017',
    projectId: 'giggleandgroww-ff499',
    storageBucket: 'giggleandgroww-ff499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFg_FTry24ev-ezlvKa4RpiEJDfg-Njzc',
    appId: '1:139042789017:ios:ec322cf378f9d6b0750a08',
    messagingSenderId: '139042789017',
    projectId: 'giggleandgroww-ff499',
    storageBucket: 'giggleandgroww-ff499.firebasestorage.app',
    iosClientId: '139042789017-htc999d89dvocpdqe7hnl75hm7fq9tqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.nwproject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCmeLvAbRfYkqsDR4d3YQoesfMCswCs4',
    appId: '1:139042789017:web:4e1230a86b81b45d750a08',
    messagingSenderId: '139042789017',
    projectId: 'giggleandgroww-ff499',
    authDomain: 'giggleandgroww-ff499.firebaseapp.com',
    storageBucket: 'giggleandgroww-ff499.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFg_FTry24ev-ezlvKa4RpiEJDfg-Njzc',
    appId: '1:139042789017:ios:ec322cf378f9d6b0750a08',
    messagingSenderId: '139042789017',
    projectId: 'giggleandgroww-ff499',
    storageBucket: 'giggleandgroww-ff499.firebasestorage.app',
    iosClientId: '139042789017-htc999d89dvocpdqe7hnl75hm7fq9tqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.nwproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABCmeLvAbRfYkqsDR4d3YQoesfMCswCs4',
    appId: '1:139042789017:web:3ca1a5acc74df5c1750a08',
    messagingSenderId: '139042789017',
    projectId: 'giggleandgroww-ff499',
    authDomain: 'giggleandgroww-ff499.firebaseapp.com',
    storageBucket: 'giggleandgroww-ff499.firebasestorage.app',
  );

}